apiVersion: execution.agenttask.io/v1alpha1
kind: AgentTask
metadata:
  labels:
    app.kubernetes.io/name: agenttask-operator
    app.kubernetes.io/managed-by: kustomize
  name: agenttask-sample
spec:
  # TODO(user): Add fields here
