apiVersion: v1
kind: ConfigMap
metadata:
  name: agenttask-runtime-profiles
  namespace: default
data:
  python3.11: "python:3.11-alpine" # Override default slim with alpine
  python3.11-sandbox: "agent-sandbox-custom:v1"
